/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zecarros;
import javax.swing.JOptionPane;
/**
 *
 * @author Vitey
 */
public class telavagas extends javax.swing.JFrame {

    /**
     * Creates new form telavagas
     */
    public telavagas() {
        initComponents();
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarvagas = new javax.swing.JButton();
        vaga1combobox = new javax.swing.JComboBox<>();
        vaga2combobox = new javax.swing.JComboBox<>();
        vaga3combobox = new javax.swing.JComboBox<>();
        vaga4combobox = new javax.swing.JComboBox<>();
        vaga5combobox = new javax.swing.JComboBox<>();
        vaga6combobox = new javax.swing.JComboBox<>();
        vaga7combobox = new javax.swing.JComboBox<>();
        vaga8combobox = new javax.swing.JComboBox<>();
        vaga9combobox = new javax.swing.JComboBox<>();
        vaga10combobox = new javax.swing.JComboBox<>();
        vaga1label = new javax.swing.JLabel();
        vaga2label = new javax.swing.JLabel();
        vaga3label = new javax.swing.JLabel();
        vaga4label = new javax.swing.JLabel();
        vaga5label = new javax.swing.JLabel();
        vaga6label = new javax.swing.JLabel();
        vaga7label = new javax.swing.JLabel();
        vaga8label = new javax.swing.JLabel();
        vaga9label = new javax.swing.JLabel();
        vaga10label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttoncadastemp = new javax.swing.JButton();
        txtcadastemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        voltarvagas.setText("Voltar");
        voltarvagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarvagasActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vaga1combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga1combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga1comboboxActionPerformed(evt);
            }
        });

        vaga2combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga2combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga2comboboxActionPerformed(evt);
            }
        });

        vaga3combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga3combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga3comboboxActionPerformed(evt);
            }
        });

        vaga4combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga4combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga4comboboxActionPerformed(evt);
            }
        });

        vaga5combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga5combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga5comboboxActionPerformed(evt);
            }
        });

        vaga6combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga6combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga6comboboxActionPerformed(evt);
            }
        });

        vaga7combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga7combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga7comboboxActionPerformed(evt);
            }
        });

        vaga8combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga8combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga8comboboxActionPerformed(evt);
            }
        });

        vaga9combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga9combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga9comboboxActionPerformed(evt);
            }
        });

        vaga10combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponível" }));
        vaga10combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaga10comboboxActionPerformed(evt);
            }
        });

        vaga1label.setText("Vaga 1");

        vaga2label.setText("Vaga 2");

        vaga3label.setText("Vaga 3");

        vaga4label.setText("Vaga 4");

        vaga5label.setText("Vaga 5");

        vaga6label.setText("Vaga 6");

        vaga7label.setText("Vaga 7");

        vaga8label.setText("Vaga 8");

        vaga9label.setText("Vaga 9");

        vaga10label.setText("Vaga 10");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zé Carros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );

        buttoncadastemp.setText("Cadastrar");
        buttoncadastemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoncadastempActionPerformed(evt);
            }
        });

        jLabel2.setText("Placa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(vaga3combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)
                            .addComponent(vaga4combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaga5label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaga4label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaga3label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaga2label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaga1label, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vaga2combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaga1combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vaga5combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(vaga6combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 176, Short.MAX_VALUE)
                                .addComponent(vaga7combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vaga8combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vaga9combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vaga10label, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vaga10combobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(vaga7label)
                            .addComponent(vaga6label)
                            .addComponent(vaga9label)
                            .addComponent(vaga8label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtcadastemp, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttoncadastemp)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga1label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga1combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga2label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga2combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga3label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga3combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga4label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga4combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga5label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vaga5combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vaga10combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vaga6label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga6combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga7label)
                        .addGap(12, 12, 12)
                        .addComponent(vaga7combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga8label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vaga8combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga9label)
                        .addGap(13, 13, 13)
                        .addComponent(vaga9combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vaga10label)
                        .addGap(34, 34, 34)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadastemp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttoncadastemp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vaga1comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga1comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga1comboboxActionPerformed

    private void vaga2comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga2comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga2comboboxActionPerformed

    private void vaga3comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga3comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga3comboboxActionPerformed

    private void vaga4comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga4comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga4comboboxActionPerformed

    private void vaga5comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga5comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga5comboboxActionPerformed

    private void vaga9comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga9comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga9comboboxActionPerformed

    private void vaga6comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga6comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga6comboboxActionPerformed

    private void vaga10comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga10comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga10comboboxActionPerformed

    private void vaga7comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga7comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga7comboboxActionPerformed

    private void vaga8comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaga8comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaga8comboboxActionPerformed

    private void voltarvagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarvagasActionPerformed
    telainicial telaInicial = new telainicial();
    telaInicial.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_voltarvagasActionPerformed

    private void buttoncadastempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoncadastempActionPerformed
    String placa = txtcadastemp.getText();
    if(txtcadastemp.getText().isEmpty()){
         JOptionPane.showMessageDialog(this, "O campo de texto está vazio!", "Aviso", JOptionPane.WARNING_MESSAGE);
    }else{
        JOptionPane.showMessageDialog(this, "Veiculo cadastrado!", "Aviso", JOptionPane.WARNING_MESSAGE);
    vaga1combobox.addItem(placa);
    vaga2combobox.addItem(placa);
    vaga3combobox.addItem(placa);
    vaga4combobox.addItem(placa);
    vaga5combobox.addItem(placa);
    vaga6combobox.addItem(placa);
    vaga7combobox.addItem(placa);
    vaga8combobox.addItem(placa);
    vaga9combobox.addItem(placa);
    vaga10combobox.addItem(placa);}
    }//GEN-LAST:event_buttoncadastempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telavagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telavagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telavagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telavagas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telavagas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoncadastemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcadastemp;
    public javax.swing.JComboBox<String> vaga10combobox;
    private javax.swing.JLabel vaga10label;
    public javax.swing.JComboBox<String> vaga1combobox;
    private javax.swing.JLabel vaga1label;
    public javax.swing.JComboBox<String> vaga2combobox;
    private javax.swing.JLabel vaga2label;
    public javax.swing.JComboBox<String> vaga3combobox;
    private javax.swing.JLabel vaga3label;
    public javax.swing.JComboBox<String> vaga4combobox;
    private javax.swing.JLabel vaga4label;
    public javax.swing.JComboBox<String> vaga5combobox;
    private javax.swing.JLabel vaga5label;
    public javax.swing.JComboBox<String> vaga6combobox;
    private javax.swing.JLabel vaga6label;
    public javax.swing.JComboBox<String> vaga7combobox;
    private javax.swing.JLabel vaga7label;
    public javax.swing.JComboBox<String> vaga8combobox;
    private javax.swing.JLabel vaga8label;
    public javax.swing.JComboBox<String> vaga9combobox;
    private javax.swing.JLabel vaga9label;
    private javax.swing.JButton voltarvagas;
    // End of variables declaration//GEN-END:variables
}
